import ConnectionLaplacian.L10_CoverCharpoly
import ConnectionLaplacian.L11_Trees
import ConnectionLaplacian.L12_WalkH1

open ConnectionLaplacian ConnGraph

#print axioms cover_charpoly_eq_scalar_times_mobius
#print axioms tree_isBalanced_of_isTree
#print axioms numComponents_of_isTree
#print axioms numBalancedComponents_of_isTree
#print axioms connectionLaplacian_kernel_dim_tree_mobius
#print axioms connectionLaplacian_kernel_dim_tree_flat
#print axioms tree_kernel_gap_zero
#print axioms isBalanced_iff_closedWalk_wrap_even
#print axioms Matrix.charpoly_conj_of_isUnit_det
